DROP USER iam;
DROP USER alex;
DROP USER mia;
CREATE USER iam LOGIN PASSWORD '12345' VALID UNTIL 'infinity' IN ROLE admin;
CREATE USER alex LOGIN PASSWORD '12345' VALID UNTIL 'infinity' IN ROLE manager;
CREATE USER mia LOGIN PASSWORD '12345' VALID UNTIL 'infinity' IN ROLE ranker;
